apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-app
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: my-react-app
          image: imane1452/my-react-app:latest
          ports:
            - containerPort: 80